const API=(window.TRACEIT_API_URL||'http://localhost:8000').replace(/\/$/,'');
const $=s=>document.querySelector(s); let record=null, metric='stress';
const token=()=>localStorage.getItem('traceit_token');
async function api(path,opts={}){const h={'Content-Type':'application/json',...(opts.headers||{})};if(token())h.Authorization=`Bearer ${token()}`;const r=await fetch(API+path,{...opts,headers:h});if(!r.ok)throw new Error((await r.json().catch(()=>({detail:r.statusText}))).detail||r.statusText);return r.json()}
function toast(t){const x=$('#toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2500)}
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function lineChart(rows,key){const box=$('#trend');const w=box.clientWidth||700,h=270,p={l:38,r:16,t:15,b:32};const vals=rows.map(x=>+x[key]);const min=Math.min(...vals),max=Math.max(...vals),range=max-min||1;const x=i=>p.l+i*(w-p.l-p.r)/Math.max(rows.length-1,1);const y=v=>p.t+(max-v)*(h-p.t-p.b)/range;let path=rows.map((r,i)=>`${i?'L':'M'} ${x(i).toFixed(1)} ${y(r[key]).toFixed(1)}`).join(' ');let dots=rows.map((r,i)=>`<circle cx="${x(i)}" cy="${y(r[key])}" r="4"/>`).join('');let labels=rows.map((r,i)=>`<text x="${x(i)}" y="${h-8}" text-anchor="middle">${esc(r.month.slice(0,3))}</text>`).join('');let grids=[0,1,2,3].map(i=>{let yy=p.t+i*(h-p.t-p.b)/3;return `<line x1="${p.l}" x2="${w-p.r}" y1="${yy}" y2="${yy}"/>`}).join('');box.innerHTML=`<svg viewBox="0 0 ${w} ${h}" preserveAspectRatio="none"><g class="grid">${grids}</g><path class="line" d="${path}"/><g class="dots">${dots}</g><g class="labels">${labels}</g><text x="${p.l}" y="11" class="axis">${metric==='stress'?'derived score':key.replace('_mg_l','').toUpperCase()}</text></svg>`}
function siteBars(sites){const max=Math.max(...sites.map(s=>s.bod),1);$('#siteBars').innerHTML=sites.map(s=>`<div class="bar-row"><b>${esc(s.site)}</b><div class="bar-track"><i style="width:${Math.min(100,s.bod/max*100)}%"></i></div><span>${s.bod}</span></div>`).join('');$('#siteTable').innerHTML=sites.map(s=>`<div><b>${esc(s.site)}</b><small>DO ${s.do} · pH ${s.ph}</small></div>`).join('');$('#sitePins').innerHTML=sites.map((s,i)=>`<div class="site-pin"><b>${esc(s.site)} <span>${s.lat.toFixed(3)}, ${s.lon.toFixed(3)}</span></b><span>BOD ${s.bod} · DO ${s.do}</span></div>`).join('');const svg=$('#lakeMap svg');sites.forEach((s,i)=>{const cx=180+i*90,cy=120+(i%2)*70;svg.insertAdjacentHTML('beforeend',`<g><circle cx="${cx}" cy="${cy}" r="7" fill="#2f5b50"/><text x="${cx+11}" y="${cy+4}" font-size="10" fill="#17302c">${esc(s.site)}</text></g>`)})}
function pcaChart(loadings,variance){const box=$('#pcaViz');const w=box.clientWidth||500,h=240,cx=w/2,cy=h/2;const scale=Math.min(w,h)*.38;let axes=[['pH',loadings[0]],['DO',loadings[1]],['BOD',loadings[2]],['TDS',loadings[3]],['COD',loadings[4]]];box.innerHTML=`<svg viewBox="0 0 ${w} ${h}"><line x1="${cx-150}" y1="${cy}" x2="${cx+150}" y2="${cy}"/><line x1="${cx}" y1="${cy-90}" x2="${cx}" y2="${cy+90}"/>${axes.map(([n,v],i)=>{let x=cx+v[0]*scale,y=cy-v[1]*scale;return `<line class="loading" x1="${cx}" y1="${cy}" x2="${x}" y2="${y}"/><text x="${x+6}" y="${y-5}">${n}</text>`}).join('')}<circle cx="${cx}" cy="${cy}" r="5"/></svg>`;$('#pcaVariance').textContent=`PC1 ${(variance[0]*100).toFixed(1)}% · PC2 ${(variance[1]*100).toFixed(1)}%`}
async function load(){try{record=await api('/api/water-bodies/1/record');const m=record.metrics,l=record.timeline.at(-1);$('#health').textContent=m.health;$('#healthbar').style.width=`${m.health}%`;$('#period').textContent=l.month;$('#do').textContent=l.do_mg_l;$('#bod').textContent=l.bod_mg_l;$('#ph').textContent=l.ph;$('#neural').textContent=m.neural_peak;$('#cph').textContent=l.ph;$('#cdo').textContent=l.do_mg_l;$('#cbod').textContent=l.bod_mg_l;$('#ctds').textContent=l.tds_mg_l;$('#ccod').textContent=l.cod_mg_l;$('#ctemp').textContent=l.temperature_c;$('#latestTitle').textContent=new Date(l.month+'-15').toLocaleString('en',{month:'long',year:'numeric'});$('#finding').textContent=`${m.bod_flagged}/${m.measurements} published observations exceed the 3 mg/L screening reference for BOD; ${m.do_flagged}/${m.measurements} are below 5 mg/L dissolved oxygen. This is a screening interpretation, not a current regulatory classification.`;siteBars(record.sites);lineChart(record.timeline,metric);const p=await api('/api/analytics/pca/1');pcaChart(p.loadings,p.explained_variance_ratio);loadActions()}catch(e){toast('Could not load record: '+e.message)}}
$('#metricTabs').addEventListener('click',e=>{if(!e.target.dataset.key)return;document.querySelectorAll('#metricTabs button').forEach(b=>b.classList.remove('active'));e.target.classList.add('active');metric=e.target.dataset.key;$('#chartNote').textContent=metric==='stress'?'Stress is a transparent derived screening signal.':'Published site measurements aggregated as four-site monthly means.';lineChart(record.timeline,metric)})
$('#observe').onclick=()=>{if(!token()){location.href='auth.html?next=dashboard.html';return}$('#modal').classList.remove('hidden')};$('#close').onclick=()=>$('#modal').classList.add('hidden');['ws','bs'].forEach(id=>$('#'+id).oninput=e=>$('#'+id+'v').textContent=e.target.value+'%');
$('#submitObs').onclick=async()=>{try{await api('/api/observations',{method:'POST',body:JSON.stringify({water_body_id:1,observed_at:new Date().toISOString(),source:'web_form',note:$('#note').value,site_code:'CITIZEN',lat:26.9565,lon:75.8465,biodiversity_signal:+$('#bs').value/100,human_signal:0,image_signal:0,quality_score:.9})});$('#modal').classList.add('hidden');$('#note').value='';toast('Observation stored in candidate-signal layer.')}catch(e){toast(e.message)}};
$('#bookmark').onclick=async()=>{if(!token()){location.href='auth.html?next=dashboard.html';return}try{const r=await api('/api/water-bodies/1/bookmark',{method:'POST'});toast(r.saved?'Record saved':'Record removed')}catch(e){toast(e.message)}};
$('#refresh').onclick=async()=>{const p=Promise.allSettled([api('/api/live/gbif'),api('/api/live/weather'),api('/api/live/usgs')]);const [g,w,u]=await p;$('#gbif').textContent=g.status==='fulfilled'?`${g.value.count??g.value.total??0} occurrences returned`:'unavailable';$('#weather').textContent=w.status==='fulfilled'?`${w.value.temperature_2m??w.value.current?.temperature_2m??'—'}°C`:'unavailable';$('#usgs').textContent=u.status==='fulfilled'?`${u.value.count??0} observations returned`:'coverage-dependent';toast('Live context refreshed where providers responded.')};
async function loadActions(){try{const a=await api('/api/water-bodies/1/interventions');$('#actions').innerHTML=a.length?a.map(x=>`<div class="action-item"><span><b>${esc(x.title)}</b><br><small>${esc(x.type)}</small></span><small>${esc(x.status)}</small></div>`).join(''):'<div class="action-item"><small>No interventions logged yet.</small></div>'}catch(e){}}
$('#addAction').onclick=async()=>{if(!token()){location.href='auth.html?next=dashboard.html';return}try{await api('/api/water-bodies/1/interventions',{method:'POST',body:JSON.stringify({title:$('#actionTitle').value,action_type:$('#actionType').value,status:'planned',notes:''})});$('#actionTitle').value='';toast('Action logged.');loadActions()}catch(e){toast(e.message)}};
$('#protocolBtn').onclick=async()=>{const p=await api('/api/water-bodies/1/protocol');toast(`${p.required_measurements.length} required measurements · ${p.steps.length} field steps`)};
window.addEventListener('resize',()=>record&&lineChart(record.timeline,metric));load();
