from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision='0001_initial'; down_revision=None; branch_labels=None; depends_on=None

def upgrade():
    op.create_table('users', sa.Column('id',sa.Integer,primary_key=True), sa.Column('name',sa.String(100),nullable=False), sa.Column('email',sa.String(190),nullable=False), sa.Column('password_hash',sa.String(500),nullable=False), sa.Column('is_active',sa.Boolean,nullable=False,server_default=sa.text('true')), sa.Column('created_at',sa.DateTime(timezone=True),nullable=False), sa.UniqueConstraint('email'))
    op.create_table('water_bodies', sa.Column('id',sa.Integer,primary_key=True), sa.Column('slug',sa.String(100),nullable=False), sa.Column('name',sa.String(160),nullable=False), sa.Column('city',sa.String(120),nullable=False), sa.Column('country',sa.String(80),nullable=False), sa.Column('latitude',sa.Float,nullable=False), sa.Column('longitude',sa.Float,nullable=False), sa.Column('status',sa.String(40),nullable=False), sa.Column('description',sa.Text,nullable=False), sa.Column('source_period',sa.String(100),nullable=False), sa.Column('created_at',sa.DateTime(timezone=True),nullable=False), sa.UniqueConstraint('slug'))
    json_type = postgresql.JSONB(astext_type=sa.Text()) if 'postgresql' in op.get_bind().dialect.name else sa.JSON()
    op.create_table('observations', sa.Column('id',sa.Integer,primary_key=True), sa.Column('water_body_id',sa.Integer,sa.ForeignKey('water_bodies.id',ondelete='CASCADE'),nullable=False), sa.Column('user_id',sa.Integer,sa.ForeignKey('users.id',ondelete='SET NULL')), sa.Column('observed_at',sa.DateTime(timezone=True),nullable=False), sa.Column('source',sa.String(80),nullable=False), sa.Column('source_record_id',sa.String(160)), sa.Column('note',sa.Text,nullable=False), sa.Column('site_code',sa.String(32),nullable=False), sa.Column('lat',sa.Float,nullable=False), sa.Column('lon',sa.Float,nullable=False), sa.Column('temperature_c',sa.Float), sa.Column('ph',sa.Float), sa.Column('tds_mg_l',sa.Float), sa.Column('do_mg_l',sa.Float), sa.Column('bod_mg_l',sa.Float), sa.Column('cod_mg_l',sa.Float), sa.Column('nitrate_mg_l',sa.Float), sa.Column('phosphate_mg_l',sa.Float), sa.Column('conductivity_us_cm',sa.Float), sa.Column('biodiversity_signal',sa.Float,nullable=False), sa.Column('human_signal',sa.Float,nullable=False), sa.Column('image_signal',sa.Float,nullable=False), sa.Column('quality_score',sa.Float,nullable=False), sa.Column('provenance',json_type,nullable=False))
    op.create_index('ix_observations_water_body_time','observations',['water_body_id','observed_at'])
    op.create_table('bookmarks', sa.Column('id',sa.Integer,primary_key=True), sa.Column('user_id',sa.Integer,sa.ForeignKey('users.id',ondelete='CASCADE'),nullable=False), sa.Column('water_body_id',sa.Integer,sa.ForeignKey('water_bodies.id',ondelete='CASCADE'),nullable=False), sa.Column('created_at',sa.DateTime(timezone=True),nullable=False), sa.UniqueConstraint('user_id','water_body_id',name='uq_user_water_body_bookmark'))
    op.create_table('incidents', sa.Column('id',sa.Integer,primary_key=True), sa.Column('water_body_id',sa.Integer,sa.ForeignKey('water_bodies.id',ondelete='CASCADE'),nullable=False), sa.Column('code',sa.String(32),nullable=False), sa.Column('detected_at',sa.DateTime(timezone=True),nullable=False), sa.Column('severity',sa.String(24),nullable=False), sa.Column('confidence',sa.Float,nullable=False), sa.Column('title',sa.String(180),nullable=False), sa.Column('summary',sa.Text,nullable=False), sa.Column('evidence_count',sa.Integer,nullable=False), sa.Column('evidence',json_type,nullable=False), sa.UniqueConstraint('code'))

def downgrade():
    for t in ['incidents','bookmarks','observations','water_bodies','users']: op.drop_table(t)
